version: '3'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - app
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOSTS=mysql-app1,wp-db
    restart: always
    ports:
      - "8090:80"
    networks:
      - app

  php-app1:
    image: alexlytle/php-app1:latest
    build:
      context: ./app1
      dockerfile: Dockerfile
      args:
        uid: 1000
    container_name: php-app1
    environment:
      - VIRTUAL_HOST=app1.donutfy.com
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    networks:
      - app

  php-app2:
    image: alexlytle/php-app2:latest
    build:
      context: ./app2
      dockerfile: Dockerfile
    container_name: php-app2
    environment:
      - VIRTUAL_HOST=app2.donutfy.com
    networks:
      - app

  react-app3:
    image: alexlytle/react-app3:latest
    build:
      context: ./app3
      dockerfile: Dockerfile
    container_name: react-app3
    environment:
      - VIRTUAL_HOST=app3.donutfy.com
    networks:
      - app

  wordpress-app4:
    image: alexlytle/wordpress-app4:latest
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    container_name: wordpress-app4
    environment:
      - VIRTUAL_HOST=app4.donutfy.com
      - WORDPRESS_DB_HOST=wp-db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    networks:
      - app

  mysql-app1:
    image: mysql:8.0
    container_name: mysql-app1
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=app1
      - MYSQL_USER=app1
      - MYSQL_PASSWORD=my-secret-pw
    volumes:
      - ./db/db:/var/lib/mysql
    networks:
      - app
  wp-db:
    image: mysql:8.0
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - wp_db:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    networks:
      - app
networks:
  app:
volumes:
  wp_db:


